Initiate variables
stephdavid/English-Helper pull request #5
Opened 2023-12-21 22:35 UTC by HillaryM17

Created variables to be used for functions. "searchInput" is currently hard set to "hello" in order to be able to run API to test, actual element ID is commented out.

2023-12-21 22:53 UTC, mattlusty requested changes
I think you want a Pull into Dev branch (not Main) :P

2023-12-21 22:58 UTC, mattlusty commented on assets/js/script.js
> +var wordDefinitionArea = $(".definition");
Non-critical improvement
Better to identify any unique elements using id attributes (and for consistency).
Although that obviously means changing the HTML (to give these ids).

2023-12-21 23:08 UTC, mattlusty commented on assets/js/script.js
> +var historyContainer = $(".previous-searches");
Could we just add a declaration for 

`var favouritesContainer;`

I know there is no HTML for the favouritesContainer yet (and may end up not even implementing it at all), but could we just declare an empty variable for it here anyway. Just so we know what variable name to reference in any "favourites" related functions.

2023-12-21 23:35 UTC, mattlusty commented on assets/js/script.js
> +var searchInput = "Hello"; //$("#search");
Ah I see why you put this here. I probably helped confuse things... 
As you have partially hinted at already, can we make this the actual element...

`var searchInputElement = $("#search");`

And leave the `var searchInputText` to be defined within the onsearch function (can just hardcode it there for now like you did on this line).

This then means having to complete the full speechURL also within the onsearch() function (see below comment)

2023-12-21 23:59 UTC, mattlusty commented on assets/js/script.js
> +const speechURL = "https://voicerss-text-to-speech.p.rapidapi.com/?key=171ec3cab6f247b4b6e7f596d9171ae7&src=" + searchInput + "&hl=en-us&r=0&c=mp3&f=8khz_8bit_mono";
Following on from above thread...

1) The main issue here, is that we will not have access to the value for searchInput (aka searchInputText) at this point. (That needs adding within the onsearch() function.)

2) Secondly, could we break the speechURL into separate pieces for clarity and easier to update things (ApiKey, and Options etc)...

```
// Speech API Query Parts
const speechBaseURL = "https://voicerss-text-to-speech.p.rapidapi.com/?
const speechApiKey = "key=171ec3cab6f247b4b6e7f596d9171ae7"
const speechOther = "&hl=en-us&r=0&c=mp3&f=8khz_8bit_mono" 
const speechOptions = {
   method: 'GET',
   headers: {
      'X-RapidAPI-Key': '6258e18b25mshd96a594dcf7fcb5p1b1fd6jsn955bae6d8f8b',
      'X-RapidAPI-Host': 'voicerss-text-to-speech.p.rapidapi.com'
   }
};

// Construct Speech API query string 
// Note: the searchInputText is left off the speechURL for now (that should be appended within the onsearch() function)
const speechURL = speechBaseURL + speechApiKey + speechOther; 

// Same needs repeating for the Word API Query 
// Question: how come this word API call does not seem to have / need an apiKey out of curiosity?

```

2023-12-22 00:01 UTC, mattlusty commented on assets/js/script.js
> +
Following on from same thread above ...

(Technically this is stepping into the onsearch() function feature... but it overlaps with the logic, so hey ho!)

function onsearch () {
   // move the searchInputText assigment here
   let searchInputText = "Hello"

   // Then append the searchInputText to complete the speechURL
   wordURL += "&src=" + searchInputText;

   // Then append the searchInputText to complete the speechURL
   speechURL += "&src=" + searchInputText;

   // then do the fetch()
}

2023-12-22 07:45 UTC, HillaryM17 commented
If we don't construct the API query call with the SearchInputText I feel it's going to confuse the issue when it comes to creating the whole URL later, splitting it into really small parts is going to cause mistakes to be made surely, especially surrounding order and adding the input,

2023-12-22 07:58 UTC, HillaryM17 commented
If we don't construct the API query call with the SearchInputText, and split it into seperate variables, I feel it's going to confuse the issue when it comes to creating the whole URL later, especially surrounding the order... 
Additionally, with the WordsURL, I don't know if we can move the SearchInputText input to the end of the URL - it doesn't look like it when I've tried to run it `Endpoint '/words/definitions/Hello' does not exist` 
The wordsURL API also isn't as complicated as the speech one as it only needs the RapidAPI key, not an additional one.  
I don't know if this makes sense written, but happy to have a conversation if it's easier :) I'm free all morning(ish).

2023-12-22 15:45 UTC, mattlusty commented
Sorry for delay response. Busy morning. I'll push it through now. 

Your code works, and most the variables are there and ready. So good job. 

Maybe we can discuss a couple of my points when your online.

2023-12-22 16:13 UTC, merged

2023-12-22 17:44 UTC, mattlusty commented on assets/js/script.js
> +var wordPronunciationArea = $("#audio");
To target the audio element (in current HTML structure) ...
`var wordPronunciationArea = $("audio#pronounciation");`
(Translates to audio element with id=pronouncitation)

2023-12-22 17:49 UTC, mattlusty commented on assets/js/script.js
> +var historyContainer = $(".previous-searches");
The element that contains the previous-search items has id #search-history-items